### ISSUE TITLE
Question about region-based 3D attention

### ISSUE THREAD

**Issue by agneet42** [wz0919/DreamRunner#1]
Hi, cool work! I had a question about the region-based 3D attention. Specifically, how do you identify which region attends to which text? Do you have a mapping of which region aligns with which text and then perform attention by masking over other regions? 
<img width="621" alt="image" src="https://github.com/user-attachments/assets/b05433c6-e3a5-4e6d-9d9a-ec1631d01ffc">

**Comment by wz0919** [comment]
Hi, thank you for your interest in our work!  

We calculate the region-text mapping based on the fine-grained plan provided by the LLM  (we convert this plan into the latent-frame space)

Yes, the attention is implemented via masking. You can refer to Figure 15 in the appendix for details on how we construct the mask.
